/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { PetFood } from "./PetFood";
import { PetFoodCountArgs } from "./PetFoodCountArgs";
import { PetFoodFindManyArgs } from "./PetFoodFindManyArgs";
import { PetFoodFindUniqueArgs } from "./PetFoodFindUniqueArgs";
import { DeletePetFoodArgs } from "./DeletePetFoodArgs";
import { PetFoodService } from "../petFood.service";
@graphql.Resolver(() => PetFood)
export class PetFoodResolverBase {
  constructor(protected readonly service: PetFoodService) {}

  async _petFoodsMeta(
    @graphql.Args() args: PetFoodCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [PetFood])
  async petFoods(
    @graphql.Args() args: PetFoodFindManyArgs
  ): Promise<PetFood[]> {
    return this.service.petFoods(args);
  }

  @graphql.Query(() => PetFood, { nullable: true })
  async petFood(
    @graphql.Args() args: PetFoodFindUniqueArgs
  ): Promise<PetFood | null> {
    const result = await this.service.petFood(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => PetFood)
  async deletePetFood(
    @graphql.Args() args: DeletePetFoodArgs
  ): Promise<PetFood | null> {
    try {
      return await this.service.deletePetFood(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
